version: '3.8'
services:
  ghost:
    image: ghost:latest
    container_name: ghostSelfMadeManContent
    environment:
      url: ${url}
      database__client: ${database__client}
      database__connection__host: ${database__connection__host}
      database__connection__user: ${database__connection__user}
      database__connection__password: ${database__connection__password}
      database__connection__database: ${database__connection__database}
      # Configuring SMTP
      # Mail
      mail__transport: ${mail__transport}
      # mail__from: staff@newsletter.self-made-man.fr
      # Options
      mail__options__service: ${mail__options__service}
      mail__options__host: ${mail__options__host}
      mail__options__port: ${mail__options__port}
      mail__options__secure: ${mail__options__secure}
      # Options.Auth
      mail__options__auth__user: ${mail__options__auth__user}
      mail__options__auth__pass: ${mail__options__auth__pass}
      #
      # mail.smtp.starttls.enable: ${mail.smtp.starttls.enable}
      # mail.smtp.starttls.required: ${mail.smtp.starttls.required}
    volumes:
      - ${GHOST_CONTENT_PATH}
    depends_on: 
      - ghost_mysql
    networks:
      - npm_network
      - self-made-man_network
    ports:
      - 8084:2368
    restart: unless-stopped

  ghost_mysql:
    image: mysql:8
    container_name: ghostSelfMadeManDB
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - self-made-man_network
    expose:
      - 3306
    volumes:
      - ${DB_VOLUME_PATH}
    restart: unless-stopped

networks:
  npm_network:
    driver: bridge
  self-made-man_network:
    driver: bridge  



