version: '3.3'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./volumes/portainer_data:/data
    # environment:
    #   - VIRTUAL_HOST=portainer.musubi.dev
    #   - VIRTUAL_PORT=9000
    ports:
      - 9443:9443
    environment:
      url: https://portainer.musubi.dev
    restart: unless-stopped
    networks:
      - npm_network

networks:
  npm_network:
    # external: true
    dirver: bridge
