version: '3.8'
services:
  conrad-design_ghost_content:
    image: ghost:latest
    container_name: ghostConradDesignContent
    ports:
      - 8011:2368
    environment:
      url: https://conrad-design.fr
      database__client: mysql
      database__connection__host: conrad-design_ghost_mysql
      database__connection__user: root
      database__connection__password: FUeylplflrK4ZA
      database__connection__database: ghost
      # Configuring SMTP
      # Mail
      mail__transport: SMTP
      # mail__from: staff@newsletter.self-made-man.fr
      # Options
      mail__options__service: Sendinblue
      mail__options__host: smtp-relay.sendinblue.com 
      mail__options__port: 587
      mail__options__secure: true
      # Options.Auth
      mail__options__auth__user: contact@conrad-edison.fr
      mail__options__auth__pass: v5n2xIE9YdzWhsV6
      #
      # mail.smtp.starttls.enable: true
      # mail.smtp.starttls.required: true
    volumes:
      - /opt/portainer/conrad-design/ghost/volumes/content:/var/lib/ghost/content
    networks:
      - npm_network
    depends_on:
      - conrad-design_ghost_mysql
    restart: unless-stopped

  conrad-design_ghost_mysql:
    image: mysql:8
    container_name: ghostConradDesignDB
    expose:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_USER: jeanLucDeLaCompta
      MYSQL_USER_PASSWORD: G2VbbJiEu3iLw
      MYSQL_ROOT_PASSWORD: FUeylplflrK4ZA
    volumes:
      - /opt/portainer/conrad-design/ghost/volumes/mysql:/var/lib/mysql
    networks:
      - npm_network
    restart: unless-stopped

networks:
  npm_network:
    driver: bridge
