version: '3.3'
services:
  youtrack:
    container_name: 'YouTrack'
    image: jetbrains/youtrack:2023.2.19783
    # volumes:
    #     - '<path'
    #     - '<path'
    #     - '<path'
    #     - '<path'
    ports:
      - 8080:8080
    networks:
      - traefik
    labels:
      - ${traefik_enable}
      - ${traefik_http_routers_rule}
      - ${traefik_http_routers_entrypoints}
      - ${traefik_http_routers_tls}
      - ${traefik_http_routers_tls_certresolver}
      - ${traefik_http_services}
      # TODO: Check for non interrupting update
      - ${watchtower_auto_update}

networks:
  traefik:
      name: traefik
      external: true