services:
  db-migration:
    container_name: oim-infisical-db-migration
    depends_on:
      db:
        condition: service_healthy
    image: infisical/infisical:latest-postgres
    env_file: .env
    command: npm run migration:latest
    pull_policy: always
    networks:
      - infisical

  backend:
    container_name: oim-infisical-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    image: infisical/infisical:latest-postgres
    pull_policy: always
    env_file: .env
    environment:
      - NODE_ENV=production
    networks:
      - infisical
      - traefik
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.infisical.rule=Host(`infisical.musubi.dev`)"
        - "traefik.http.routers.infisical.entrypoints=websecure"
        - "traefik.http.routers.infisical.tls=true"
        - "traefik.http.routers.infisical.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.infisical.loadbalancer.server.port=8080"
        
  redis:
    image: redis
    container_name: oim-infisical-dev-redis
    env_file: .env
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    networks:
      - infisical
    volumes:
      - redis_data:/data

  db:
    container_name: oim-infisical-db
    image: postgres:14-alpine
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - infisical
    healthcheck:
      test: "pg_isready --username=${POSTGRES_USER} && psql --username=${POSTGRES_USER} --list"
      interval: 5s
      timeout: 10s
      retries: 10

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  traefik:
    external: true
  infisical:
