services:
  traefik:
    image: traefik:2.11
    container_name: "traefik"
    networks:
      - traefik
    ports:
      - "80:80" # HTTP
      - "443:443" # HTTPS
      # Prometheus metrics endpoint
      # - "9100:9100"
      # Epitech
      - "4210:4210" # TCP Postgres T-POO-700-LIL_5
      - "4000:4000" # API
    volumes:
      - letsencrypt:/letsencrypt
      # - ./traefik.yml:/etc/traefik/traefik.yml
      - ./dynamic.yml:/dynamic.yml
      - ./users.u:/users/users.u
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    command:
      - "--accesslog=true"
      - "--log.level=DEBUG"
      # Prometheus
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.buckets=0.1,0.3,1.2,5.0"
      # Docker configuration
      - "--providers.docker=true"
      - "--providers.docker.watch=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik"
      # Configure entrypoint
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.pooger-pg.address=:4000" # Epitech
      # SSL configuration
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencryptresolver.acme.httpchallenge.entrypoint=web"
     # - "--certificatesresolvers.letsencryptresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.letsencryptresolver.acme.email=thibaut.raphael@protonmail.com"
      - "--certificatesresolvers.letsencryptresolver.acme.storage=/letsencrypt/acme.json"
      # Global HTTP -> HTTPS
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      # Express API
      - "--providers.file.filename=/dynamic.yml"

      # Traefik plugins
      # - "--configfile=/etc/traefik/traefik.yml"
      # Middleware basicAuth
      # - "http.middlewares.simple-auth.basicAuth.users=<USERNAME:PASSWORD_HASH>"
      # TCP
      # - "--entrypoints.pooger-pg.address=:4210"
      # Enable dashboard
      - "--api.dashboard=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencryptresolver"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=dashboard-auth"
      - "traefik.http.middlewares.dashboard-auth.basicauth.usersfile=/users/users.u"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.musubi.dev`)"
      - "traefik.http.services.dashboard.loadbalancer.server.port=8080"
      # WatchTower auto update
      # TODO: Check for non interrupting update
      - "com.centurylinklabs.watchtower.enable=true"

      # Nextcloud
      # - "traefik.http.routers.nextcloud.entrypoints=websecure" # Corrected router name to match service name
      # - "traefik.http.routers.nextcloud.tls=true"
      # - "traefik.http.routers.nextcloud.tls.certresolver=letsencryptresolver"
      # - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.musubi.dev`)" # Corrected router name
      # - "traefik.http.services.nextcloud.loadbalancer.passHostHeader=true" # Corrected service name
      # - "traefik.http.services.nextcloud.loadbalancer.server.url=http://192.168.100.11:80"
      # - "traefik.http.routers.nextcloud.service=nextcloud"

      # homepage
      # - "traefik.http.routers.testjs.entrypoints=websecure" # Corrected router name to match service name
      # - "traefik.http.routers.testjs.tls=true"
      # - "traefik.http.routers.testjs.tls.certresolver=letsencryptresolver" 
      # - "traefik.http.routers.testjs.rule=Host(`testjs.musubi.dev`)" # Corrected router name
      # - "traefik.http.services.testjs.loadbalancer.server.url=http://172.17.0.1:3000"
      # - "traefik.http.services.testjs.loadbalancer.server.port=3000"

networks:
  traefik:
    external: true
    
volumes:
  letsencrypt:
    external: true

